baseURL = "http://www.christophliedtke.com/"
languageCode = "en-us"
title = "HCL | Life History Evolution"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1
[[menu.main]]
name    = "Projects"
url     = "portfolio"
weight  = 2
[[menu.main]]
name    = "Publications"
url     = "publications"
weight  = 3
[[menu.main]]
name    = "People"
url     = "people"
weight  = 4
[[menu.main]]
name    = "CV"
url     = "cv"
weight  = 5
[[menu.main]]
name    = "R code"
url     = "https://hcliedtke.github.io/R-scrapheap/"
weight  = 6
[[menu.main]]
name    = "Field Blog"
url     = "blog"
weight  = 7
[[menu.main]]
name    = "Wildlife"
url     = "gallery"
weight  = 8
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 9

# Site Params
[params]
home = "Home"
logo = "images/hcl_logo3.png"
dateFormat = "6 January 2006"
# Meta data
description = "HCL logo"
author = "Christoph Liedtke"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "https://formspree.io/f/xqkwqaaw" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/leptopelis_banner.jpg"
heading = "Amphibian"
description = ""
# button
btn     = false
btnText = "Find out more"
btnURL  = "/gallery/"

# flip text
[[params.banner.flipText]]
title   = "Evolution"
[[params.banner.flipText]]
title   = "Life History"
[[params.banner.flipText]]
title   = "Eco-Evo-Devo"
[[params.banner.flipText]]
title   = "Transcriptomics"
[[params.banner.flipText]]
title   = "Genomics"
[[params.banner.flipText]]
title   = "Systematics"
[[params.banner.flipText]]
title   = "Biogeography"
[[params.banner.flipText]]
title   = "Photography"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"
content = "I am a Juan de la Cierva postdoctoral researcher at the Estación Biológica de Doñana, in Seville, Spain. I am a member of Ivan Gomez-Mestre's <a href='https://www.eco-evo-devo.com/' target='_blank'>Ecology, Evolution and Development Group</a>. I am interested in applying different approaches to studying trait evolution at different scales. My three main research lines are centred on (1) describing macroevolutionary patterns in trait evolution through the use of comparative phylogenetic methods, (2) using transcriptomic and epigenetic approaches to study the role of adaptive plasticity in trait evolution, and (3) studying the systematics and biogeography of African amphibians. </br> </br> I completed my PhD at the University of Basel in Switzerland, studying the accumulation of amphibian lineages in Africa and whether aspects of life history (specifically terrestrial breeding) have evolved in response to specific environmental conditions. I continue to conduct <a href='/blog'>field work in tropical forests across Africa</a> whenever I can, which I thoroughly enjoy."
image   = "images/about/hcl_profile.png"

# Call to Action
[params.cta]
enable  = false
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Featured Projects"
subtitle= ""

# social icon
#[[params.socialIcon]]
#icon = "ion-social-facebook"
#url = "#"
#
#[[params.socialIcon]]
#icon = "ion-social-instagram"
#url = "#"
#
#[[params.socialIcon]]
#icon = "ion-social-linkedin"
#url = "#"

# allow raw html in markdown index_files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
